---
title: "שיטות זיהוי מחזור פיננסי"
author: "מיכאל גורקוב"
header-includes:
   - \usepackage{multirow,rotating}
   - \usepackage{fontspec}
   - \setmainfont{David}
   - \usepackage{polyglossia}
   - \setdefaultlanguage{hebrew}
   - \usepackage[fontsize=13pt]{scrextend}
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r Import data,libraries and functions}

source(paste0("C:\\Users\\Misha\\Documents\\BBQ-Algorithm\\",
              "BBQ-Auxilary functions.R"))

library(xts)

library(PerformanceAnalytics)

gdp = import.gdp.data(paste0("C:\\Users\\Misha\\Documents\\",
                             "BBQ-Algorithm\\GDP.csv"))

```



שיטות לזיהוי מחזור עסקים מתחלקות לשני סוגים: שיטות Turning Point ושיטותFrequency Analysis


<!-- ```{r plot } -->

<!-- # Identify a set of potential peaks and troughs -->

<!-- df = cbind.xts(gdp,rollapply(gdp, width = 5, FUN = identify.turning.point, -->
<!--                         align = "center")) -->

<!-- names(df) = c("GDP","TP") -->

<!-- alt.peaks = get.alternating.peaks(peaks = df[df$TP == 1,], -->
<!--                                   troughs = df[df$TP == -1,], -->
<!--                                   timeframe = index(df)) -->

<!-- alt.troughs = get.alternating.troughs(peaks = df[df$TP == 1,], -->
<!--                                   troughs = df[df$TP == -1,], -->
<!--                                   timeframe = index(df)) -->

<!-- cycle_date = paste(as.Date(index(alt.peaks)), -->
<!--                    as.Date(index(alt.troughs)),sep = "/") -->

<!-- chart.TimeSeries(df$GDP * 10 ^ (-3), -->
<!--                  main = "Business Cycle - Recessions\n (quarterly GDP)", -->
<!--                  xaxis = FALSE,ylab = "Billions ILS", -->
<!--                  period.areas = cycle_date,period.color = "lightblue") -->

<!-- axis(side = 1,at = seq_along(index(df)),labels = index(df)) -->


<!-- ``` -->

